title: "Jekyll Practice"
logo: ./img/room_bwelgi.gif
description: "test or practice"

baseurl: "jekyllpractice"
url: "https://redder0125.github.io"
author: Redder

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
